### ISSUE TITLE
Not Working Correctly With Akai APC40 MIDI Controller

### ISSUE THREAD

**Issue by Ruebinb** [lebaston100/MIDItoOBS#20] opened 2020-04-17 02:42 UTC
I'm having trouble mapping the faders to the volume control. If I map one fader it maps every fader to the same volume control.

**Comment by lebaston100** [comment] 2020-04-17 07:56
I've read though the protocol documentation of your device and found out that the default midi mapping has the same control value for all the fader, with the difference beeing the midi channel which MIDItoOBS currently will ignore by design:

> These knobs and switches will output on a different MIDI channel based on the current Track Selection (track 1 = MIDI channel 0, track 8 = MIDI channel 7, MASTER = MIDI channel 8)

It also doesn't seem to be possible to reconfigure the faders with some software from Akai.
So right now you won't be able to use them. I will look into what needs to be done to finally add support for midi channels though.
I will leave this open for now until there is a solution.

It would be really helpfull for me if you could join the discord at [https://discord.gg/PCYQJwX](https://discord.gg/PCYQJwX) and message me there so we can debug furter.

**Comment by lebaston100** [comment] 2020-04-25 08:48
I have added midi channel handling now. Could you give it a try again?
https://github.com/lebaston100/MIDItoOBS/archive/master.zip

**Comment by dakahl** [comment] 2020-05-10 13:42
Nice, I use the APC20 MIDI Controller. And not it works perfect with the channel setting. Thanks

**Comment by lebaston100** [comment] 2020-05-10 14:20
Glad that it works now.
I will put that other thing on my todo list. I plan on redoing the data model to support more advanced use anway sooner or later.
I'll close this for now.

**Closed by lebaston100** 2020-05-10 14:20 UTC
